### ISSUE TITLE
Proposal update with no Image Classification has some few remains of image portion

### ISSUE THREAD

**Issue by thegauravgiri** [featherfind/docs#3]
List of figures has FeatherFing instead of FeatherFind due to incorrect captioning. 
<img width="748" alt="Screenshot 2024-06-27 at 11 41 53 PM" src="https://github.com/featherfind/docs/assets/64427471/17b76b96-658a-497c-8747-43159e06e787">

<hr>

Abstract Section still contains the sentences describing about the image classification.
<img width="732" alt="Screenshot 2024-06-27 at 11 42 19 PM" src="https://github.com/featherfind/docs/assets/64427471/8a2e8bdd-e9f8-4139-9a97-cdad40b73f0c">

<hr>

Methodology section still describes that there will be two working mechanism.
<img width="695" alt="Screenshot 2024-06-27 at 11 43 29 PM" src="https://github.com/featherfind/docs/assets/64427471/f6eea9ab-82f8-4640-b0cb-fe85fb130a4c">

<hr>

Need to change the usecase diagram by removing the "take image" part.
<img width="264" alt="Screenshot 2024-06-27 at 11 45 17 PM" src="https://github.com/featherfind/docs/assets/64427471/bdcdc02a-f5ec-45fd-9318-66e745f0190d">

**Comment by iamiza** [comment]
Done

**Comment by thegauravgiri** [comment]
Nice!
